### ISSUE TITLE
CS8336:  'Microsoft.CodeAnalysis.EmbeddedAttribute' is reserved

### ISSUE THREAD

**Issue by PBeckmann-prohandel** [Sergio0694/PolySharp#143]
### Description (optional)

When building our source generator project we get this compiler error:
`/opt/atlassian/pipelines/agent/build/SourceGenerators/obj/Debug/netstandard2.0/PolySharp.SourceGenerators/PolySharp.SourceGenerators.PolyfillsGenerator/Microsoft.CodeAnalysis.EmbeddedAttribute.g.cs(15,35): error CS8336: The type name 'Microsoft.CodeAnalysis.EmbeddedAttribute' is reserved to be used by the compiler.`

### Reproduction Steps

The content of the csproj.
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
      <TargetFramework>netstandard2.0</TargetFramework>		
      <LangVersion>latest</LangVersion>		
      <Nullable>enable</Nullable>		
      <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
      <IsRoslynComponent>true</IsRoslynComponent>
      <IncludeBuildOutput>false</IncludeBuildOutput>		
      <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
      <IsRoslynComponent>true</IsRoslynComponent>	
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="*">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.11.0" />
    <PackageReference Include="PolySharp" Version="1.16.*">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
```

Reverting to 1.15.* fixes the compile error.

### Expected Behavior

No compile errors

### Actual Behavior

Compile error CS8336 occurrs

### System info
- **PolySharp** 1.16.0
- Bitbucket pipeline with image tag `mcr.microsoft.com/dotnet/sdk:8.0`

**Comment by ivarne** [comment]
I'm also getting this when building from command line, but apparently not when building in rider. I'm using net8.0 on a Mac if that matters.

**Comment by PBeckmann-prohandel** [comment]
We also do not get this error when building in Visual Studio 2026 on Windows 11

**Comment by Sergio0694** [comment]
The issue happens if you build with Roslyn < 4.14. I'll need to add a check to disable the attribute in that case.
The workaround is to set `PolySharpUseEmbeddedAttributeForGeneratedTypes=false` for now if you're on old Roslyn.
